# Generated by Django 2.1.15 on 2021-06-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('open', models.BooleanField(default=True)),
                ('suspended', models.IntegerField(default=0)),
                ('abonnes', models.ManyToManyField(related_name='communautes', to=settings.AUTH_USER_MODEL)),
                ('banned', models.ManyToManyField(blank=True, related_name='communautes_banned', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(related_name='communautes_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communaute',
            },
        ),
        migrations.CreateModel(
            name='Lecteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecteur',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('evenementiel', models.BooleanField()),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=True)),
                ('sticky', models.BooleanField(default=False)),
                ('avertissement', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('communaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Communaute')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('degre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Priorite',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Priorite'),
        ),
        migrations.AddField(
            model_name='lecteur',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Post'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communitymanager.Post'),
        ),
    ]
