# Generated by Django 2.1.15 on 2021-05-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communaute',
            options={'verbose_name': 'Communautes'},
        ),
    ]
