# Generated by Django 2.1.15 on 2021-05-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0002_auto_20210518_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communaute',
            options={'verbose_name': 'Communaute'},
        ),
    ]
