# Generated by Django 2.1.15 on 2021-05-24 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0007_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
