# Generated by Django 2.2 on 2021-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0009_auto_20210526_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorite',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
