# Generated by Django 2.1.15 on 2021-05-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0009_auto_20210526_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorite',
            name='degre',
            field=models.IntegerField(default=0),
        ),
    ]
