# Generated by Django 2.1.15 on 2021-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0010_auto_20210527_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
