# Generated by Django 2.1.15 on 2021-05-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0011_auto_20210527_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
