# Generated by Django 2.1.15 on 2021-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0012_commentaire_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='suspended',
            field=models.IntegerField(default=0),
        ),
    ]
