# Generated by Django 2.1.15 on 2021-05-31 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0013_communaute_suspended'),
        ('communitymanager', '0010_priorite_degre'),
    ]

    operations = [
    ]
