# Generated by Django 2.1.15 on 2021-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0014_merge_20210531_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avertissement',
            field=models.BooleanField(default=False),
        ),
    ]
