# Generated by Django 2.2 on 2021-05-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0010_priorite_ordre'),
        ('communitymanager', '0014_merge_20210531_1120'),
    ]

    operations = [
    ]
