# Generated by Django 2.1.15 on 2021-05-31 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0015_post_avertissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='communaute',
            name='banned',
            field=models.ManyToManyField(related_name='communautes_banned', to=settings.AUTH_USER_MODEL),
        ),
    ]
