# Generated by Django 2.2 on 2021-06-02 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0015_merge_20210531_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorite',
            name='ordre',
        ),
        migrations.AddField(
            model_name='post',
            name='lecteurs',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
