# Generated by Django 2.1.15 on 2021-06-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0016_auto_20210602_1039'),
        ('communitymanager', '0016_communaute_banned'),
    ]

    operations = [
    ]
