# Generated by Django 2.1.15 on 2021-05-31 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0016_communaute_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communaute',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='communautes_banned', to=settings.AUTH_USER_MODEL),
        ),
    ]
