# Generated by Django 2.1.15 on 2021-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0017_auto_20210531_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
