# Generated by Django 2.1.15 on 2021-06-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0017_post_lu'),
        ('communitymanager', '0018_auto_20210601_0826'),
    ]

    operations = [
    ]
