# Generated by Django 2.1.15 on 2021-06-04 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0018_merge_20210604_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
