# Generated by Django 2.1.15 on 2021-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0019_auto_20210604_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
