# Generated by Django 2.1.15 on 2021-06-02 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0020_auto_20210602_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lecteurs',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
